### ISSUE TITLE
docker pull limit refrence

### ISSUE THREAD

**Issue by jingjingxyk** [eryajf/Thanks-Mirror#3]
## 未订阅用户：
> 未登录用户，每 6 小时只允许 pull 100 次

>已登录用户，每 6 小时只允许 pull 200 次

## 方法一：使用代理缓存镜像
```
version: "3"
services:
    docker-registry:
        image: registry:2
        container_name: registry-01
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - /data/tls:/tls
            - /data/docker-registry:/data
        environment:
            - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
            - REGISTRY_PROXY_USERNAME=username
            - REGISTRY_PROXY_PASSWORD=password
            - REGISTRY_HTTP_TLS_CERTIFICATE=/tls/wildcard.domain.com.fullchain.pem
            - REGISTRY_HTTP_TLS_KEY=/tls/wildcard.domain.com.key.pem
            - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
            - http_proxy=http://http-yaokun-proxy.domain.com:1080  # http proxy 
            - https_proxy=http://http-yaokun-proxy.domain.com:1080 # http proxy


```

## 方法二：使用代理 registry-1.docker.io地址
```
version: "3"
services:
    docker-registry:
        image: registry:2
        container_name: registry-02
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - /data/app/tls:/tls
            - /var-lib-containerd/docker-registry:/data
        environment:
            - REGISTRY_PROXY_REMOTEURL=https://docker-registry-mirror.domain.com # user nginx proxy registry-1.docker.io
            - REGISTRY_PROXY_USERNAME=username
            - REGISTRY_PROXY_PASSWORD=password
            #      - REGISTRY_PROXY_REMOTEURL=https://mirror.gcr.io    # user nginx proxy mirror.gcr.io
            #      - REGISTRY_PROXY_REMOTEURL=https://k8s.gcr.io       # user nginx proxy k8s.gcr.io
            #      - REGISTRY_PROXY_REMOTEURL=https://gcr.io              # user nginx proxy gcr.io
            - REGISTRY_HTTP_TLS_CERTIFICATE=/tls/wildcard.domain.com.fullchain.pem
            - REGISTRY_HTTP_TLS_KEY=/tls/wildcard.domain.com.key.pem
            - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data


```
